### ISSUE TITLE
Contribution process?

### ISSUE THREAD

**Issue by sknebel** [JannesMeyer/TabAttack#1]
Hi!

I'm thinking about modifying TabAttack for my own needs, but some of the changes might be of general interest. Do you have any preferences how you'd like to discuss and receive changes? If yes, it might be a good idea to add that to the README as well

**Comment by jmfayard** [comment]
Interested too!

Can we discuss by email?

**Comment by JannesMeyer** [comment]
Hi, author here! Sorry for the delay. Something in my GitHub settings was messed up and I didn't get any notifications.

This is just a small tool that I built for myself, but my goal is to make it useful for as many other people as possible, so I'm very open to ideas that align with the spirit of this project – which is improving the tab management in Chrome.

Feel free to drop me a line at the email address I have in my profile if you want to discuss any ideas.

Pull requests and issues on GitHub are very welcome for anything that is of general interest. Your code should adhere to the formatting of the rest of the project and it should work with the current build process (i.e. webpack). Other than that there is not much to say, I think.

I will keep this issue open until I add a contributions section to the readme.
