### ISSUE TITLE
3-digit tab number display broken

### ISSUE THREAD

**Issue by sknebel** [JannesMeyer/TabAttack#10]
Looks now like this:
![image](https://cloud.githubusercontent.com/assets/1082036/6315143/bb70a40a-b9f8-11e4-9c03-de427341990c.png)

I'm investigating it, something with the fonts seems to go wrong...

**Comment by JannesMeyer** [comment]
Sorry about that! I specifically tested it on my machine before releasing the update.

Which operating system are you using? I am on OSX. Maybe the Windows version of Chrome is using a different font renderer.

**Comment by sknebel** [comment]
Windows 8.1. The distance between individual characters seemed quite high to me in some cases, but font setup etc looked fine. I have no idea what's going on exactly...
