### ISSUE TITLE
Fix domain blacklist (in options)

### ISSUE THREAD

**Issue by JannesMeyer** [JannesMeyer/TabAttack#2]
Currently the domain blacklisting in the options doesn't do anything

**Comment by sknebel** [comment]
Do I miss something, or is this not solved yet? As far as I can tell @trenton42's pull request only enables saving the filter list in the options, but it isn't actually used.

**Comment by trenton42** [comment]
@sknebel Correct, the blacklists aren't fixed yet.

**Comment by JannesMeyer** [comment]
Yep, sorry about that. Somehow the issue got closed automatically when I merged the pull request. I am actually finishing the blacklist right now. I expect to release 1.3 to the chrome web store tonight.

**Comment by trenton42** [comment]
:+1:
