### ISSUE TITLE
Export as pretty JSON.

### ISSUE THREAD

**Issue by n370** [JannesMeyer/TabAttack#5]
Would be pretty amazing to have an option to export them as a pretty JSON array.

i.e.

```
[
  {
    "title" : "GitHub",
    "url" : "https://github.com/"
  }
]
```

**Comment by JannesMeyer** [comment]
Hi n370, thanks for the feature request. Yes, I could add that as an option.

Is it correct that you prefer JSON over Markdown 100% of the time? I just wanna make sure that I understand your use-case correctly. So if I added an option called "Export format" in the settings that would work for you?

**Comment by n370** [comment]
Hi @JannesMeyer , it's great to hear from you. Yes, yes, yes a settings option like that would be perfect. Let me explain my actual workflow managing tabs and how your project is a big deal for me.

Before trying TabAttack I used to daily save bookmark folders with as much as I could of the pages I visited during the day. Usually it works fine but when I'm browsing unsynchronised it becomes a pain because chrome doesn't allow me to export bookmarks in a folder by folder basis.

On top of that, lately I've been thinking about writing an application aiming to backup and consolidate bookmarks independent of browsers. FF has built in an export as JSON option but with Chrome the best you get is the `Bookmarks` file which resides on OS X systems inside `~/Library/Application\ Support/Google/Chrome/Profile` and that's ugly. 

FF bookmark object looks like this.

```
{
  "guid": "HRnFxFQvgnl5",
  "title": "Getting Started",
  "index": 3,
  "dateAdded": 1423582240876495,
  "lastModified": 1423582240876495,
  "id": 14369,
  "type": "text/x-moz-place",
  "uri": "https://www.mozilla.org/en-US/firefox/central/"
}
```

And Chrome comes like that.

```
{
  "date_added": "13054512181000000",
  "id": "13958",
  "meta_info": {
    "stars.id": "ssc_654f3e248659492d",
    "stars.isSynced": "true"
  },
  "name": "Future Fins Surf Board Technology",
  "sync_transaction_version": "2285",
  "type": "url",
  "url": "http://www.futuresfins.com/index.php"
}
```

To answer your question, no. I'm strongly thinking about switching my workflow to "attacking" tabs instead of bookmarking them. The markdown files are really light and dropbox is giving me a parsed view that works like a charm. I could really fill you with plenty of feature requests just because browsing is so central to my workflow, I do it heavily on a daily basis and to be able to manage bookmarks light and fast is core for me. One caveat I can think about now is that I won't be able to search inside multiple files at once through the dropbox web interface, but maybe I could just use `Finder` locally to do that.

Thanks for getting in touch and coming up with this project. Let me know If I can be helpful somehow.

**Comment by JannesMeyer** [comment]
For exporting bookmarks from Chrome there is actually a specific API for accessing them: [chrome.bookmarks.getTree](https://developer.chrome.com/extensions/bookmarks#method-getTree). If you used that you wouldn't have to go through the extra step of opening all your bookmarks as tabs to be able to export them. But I'm not sure that this extension would be the right place for anything bookmark-related.

What I'm personally doing is avoiding the Chrome bookmarks altogether and storing my bookmarks in Markdown in a kind of personal wiki. (Which is a big reason why I made this extension)

Spotlight indexing works for Markdown files, as long as you have at least one (Markdown-related) app installed that registers the correct MIME type in the system for .md files. 

One project that I'm thinking about for the future is improving Markdown search in OSX using [mdfind](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/mdfind.1.html), but I don't have any specific plans yet.

**Comment by n370** [comment]
Danke @JannesMeyer! Amazing code, great tool.

**Comment by n370** [comment]
Hey @JannesMeyer , how is it going? FYI since I started using this tool I've pretty much stick with it abandoning chrome's bookmark utility. I have mostly exported my lists as markdown files that I search inside for keywords from my terminal command line using `$ grep -iR "<keyword>" .`  Still couldn't  find time to contribute code here but use the tool everyday. GREP is working great as a bookmarks search tool.

**Comment by JannesMeyer** [comment]
Hi n370,

Glad to hear you are liking the project! Let me know if there is any feature you are missing. I'm always happy about good suggestions :)
